// types for the authentication 

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOAD_PROFILE = "LOAD_PROFILE";


//types for the videos

export const HOME_VIDEOS_SUCCESS = "HOMEVIDEOS_SUCCESS";
export const HOME_VIDEOS_FAILED = "HOMEVIDEOS_FAILED";
export const HOME_VIDEOS_REQUEST = "HOMEVIDEOS_REQUEST";

//types for the specific video selected by the use to play

export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_FAILED = "SELECTED_VIDEO_FAILED";

//types for the channel details

export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_FAILED = "CHANNEL_DETAILS_FAILED";

//types for the subscriptionsStatus check
export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

//types for the comment thread action
export const COMMENT_THREAD_REQUEST = "COMMENT_THREAD_REQUEST";
export const COMMENT_THREAD_SUCCESS = "COMMENT_THREAD_SUCCESS";
export const COMMENT_THREAD_FAILED = "COMMENT_THREAD_FAILED";

//types for replies to comments
export const COMMENT_REPLIES_REQUEST = "COMMENT_REPLIES_REQUEST";
export const COMMENT_REPLIES_SUCCESS = "COMMENT_REPLIES_SUCCESS";
export const COMMENT_REPLIES_FAILED = "COMMENT_REPLIES_FAILED";

//types for the insert comment action
export const INSERT_COMMENT_SUCCESS = "INSERT_COMMENT_SUCCESS";
export const INSERT_COMMENT_FAILED = "INSERT_COMMENT_FAILED";

//types for getting similar videos
export const SIMILAR_VIDEOS_REQUEST = "SIMILAR_VIDEOS_REQUEST";
export const SIMILAR_VIDEOS_SUCCESS = "SIMILAR_VIDEOS_SUCCESS";
export const SIMILAR_VIDEOS_FAILED = "SIMILAR_VIDEOS_FAILED";

//types for user searches
export const USER_SEARCH_INPUT_REQUEST = "USER_SEARCH_INPUT_REQUEST";
export const USER_SEARCH_INPUT_SUCCESS = "USER_SEARCH_INPUT_SUCCESS";
export const USER_SEARCH_INPUT_FAILED = "USER_SEARCH_INPUT_FAILED";

//types for subscription videos
export const SUBSCRIPTION_VIDEOS_REQUEST = "SUBSCRIPTION_VIDEOS_REQUEST";
export const SUBSCRIPTION_VIDEOS_SUCCESS = "SUBSCRIPTION_VIDEOS_SUCCESS";
export const SUBSCRIPTION_VIDEOS_FAILED = "SUBSCRIPTION_VIDEOS_FAILED";
